### ISSUE TITLE
PRS7000MenasM

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1151] opened 2019-04-29 13:13 UTC
there seems to be a problem with PRS7000MenasM, the record existed twice (once in 6001-7000 and once in 7001-8000), I now deleted one and moved the more updated one to the correct folder but the app now shows "Sorry! PRS7000MenasM has been marked as deleted." on https://betamasaheft.eu/persons/PRS7000MenasM/main

**Comment by PietroLiuzzo** [comment] 2019-04-29 15:28
Eventually, this is a feature, not a bug! the list of deleted entries is working properly and reports that the item has been deleted even before looking for it, because it has been correctly marked as deleted when the event occurred. I have modified the deleted items list so you can see the file which is actually there...

**Comment by thea-m** [comment] 2019-05-02 10:26
also in the authority files for AT1131MMWoman and all other recently created art themes :) it is probably recognising as deleted all files that were moved from one folder to another?

**Comment by eu-genia** [comment] 2019-05-09 09:35
would deleting all occurrences and, after syncing, pushing one correct one, solve the problem?

**Comment by PietroLiuzzo** [comment] 2019-05-09 12:56
no, and workarounds are not the way we should work any way. you will simply have to be so kind as to wait for me to get to this and correct this behaviour for files which are moved and not deleted.

**Comment by PietroLiuzzo** [comment] 2019-06-19 09:40
please, give it a go now, the script should be fixed

**Closed** 2019-06-19 09:40 UTC

**Comment by thea-m** [comment] 2019-06-19 12:00
thank you! the concerned records are now normally shown on the app, but the Art Theme records aren't yet listed here https://betamasaheft.eu/authority-files/list under Art Themes
