### ISSUE TITLE
title type="main" not printed as main title

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1368] opened 2020-03-23 12:33 UTC
What do you see?
- I see the Fidel title printed as the main one instead of the main type (which is not printed at all?)
Can you please give a link to an example?
LIT5859HomilyBlind
What is wrong with it?
The main printed title should be the English one, for works just like the persons etc.

**Comment by PietroLiuzzo** [comment] 2020-03-23 16:45
the xml in the DB does not have another title. perhaps the upload has gone wrong?
https://betamasaheft.eu/works/LIT5859HomilyBlind.xml

**Comment by PietroLiuzzo** [comment] 2020-03-23 16:48
if you have edited this, it is not in master yet.

**Comment by eu-genia** [comment] 2020-03-24 09:46
oops has not been merged yet. And what about this one? PRS12817Anestasyos? which is the printed element?

**Comment by PietroLiuzzo** [comment] 2020-03-24 16:04
the rules have not been changed and are documented here 
https://betamasaheft.eu/Guidelines/?id=persons, but I have changed the code and clearly there is some error in that part, namely the static list does not update as expected on changes to the entries which impact the printed title.

**Comment by PietroLiuzzo** [comment] 2020-03-24 16:35
I could not reproduce the update because the merge was apparently not squash merged but only merged. however I have fixed the code and hand fixed the list for this record. I will however periodically update anyway the full static list.

**Comment by PietroLiuzzo** [comment] 2020-03-24 16:37
please also note that for persons files, as by the guidelines, the file name is not taken into consideration at all, so changing title inside titleStmt has no effect anywhere.

**Closed** 2020-04-22 08:03 UTC
Labels: app
