### ISSUE TITLE
definition of decoration types in the schema

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#888] opened 2018-05-17 13:39 UTC
It would be extremely useful if short definitions could be added to the types of decorations listed in the schema:
frame
miniature
band
punctuation
drawing
border
diagram
frieze
illustration
initial
map
marginal
mixed
other
ornamentation
paratext
printmark
publishmark
secondary
tooling
unspecified
unwan
vignette
engraving

Maybe the list needs to be updated as well.
I am not really qualified to do this, would it maybe be possible for you @DenisNosnitsin1970 or @Gnisci ? It would really be helpful. thank you!

**Comment by thea-m** [comment] 2018-05-17 13:44
maybe a type for images glued to mss could then also be defined #843

**Comment by eu-genia** [comment] 2018-05-17 13:57
In addition to the list, many E-S mss descriptions have among "extras" (not among decoration, since clearly these are not part of the book design) things like `"doodles"` (I guess meaning crude drawings by users).  Should these be left without further encoding or is it worth it to somehow structure the information?

**Comment by thea-m** [comment] 2018-05-17 14:05
I think that we encode them as well as "extras" (in additions), at least they are listed in the guidelines in the list inherited from ethiospare (and just only slighly edited by me)
http://betamasaheft.eu/Guidelines/?id=additionsVaria

**Comment by Gnisci** [comment] 2018-08-03 08:15
Hello @thea-m thea, for some reason, I was not notified of this, let me look into it ASAP

**Comment by thea-m** [comment] 2018-08-03 08:25
thank you, @Gnisci ! Take your time :)

**Comment by Gnisci** [comment] 2018-08-07 08:41
Most terms are clear, and I would be happy to provide definitions for them. In some cases, things are less clear, and I need some clarifications in order to proceed:

1. Miniature and illustration could be the same thing. Is it useful to maintain a distinction?
2. Frame can be a number of things, do you have any examples of how it has been used so far? It can be a band encircling a miniature as well as a geometric pattern surrounding the incipit of a text.
3. Border, has this been used in a manner that differs from frame and band?
4. Frieze, I don't see much use in retaining this term, when we have "band" that seems to me more appropriate for a manuscript
5. Vignette, I don't see how this beneficial it would be to use this. Has it been used?
6. Ornamentation, has this been used to refer to the decorative patterns within a band/frame?

**Comment by thea-m** [comment] 2018-08-07 11:07
Thank you Jacopo! Maybe it would be good to wait for @DenisNosnitsin1970 's opinion when he's back next week, as I didn't work much with decorations.
Just for now, as far as I can see:
- Frieze and vignette have not been used at all (I don't know where this list originates, maybe some of its items are not relevant for us). 
- Border as a value has only been used in BAVet53 and BAVet15, where it seems to describe a band.
- Frame has been used widely, especially in the updated Ethio-Spare records, where the description then speaks of "ornamental band" (e.g. ESagm003), mostly I believe for describing the patterns surrounding the incipit.
- Band has been used mainly in our new records, with descriptions not differing from "frame".

**Comment by DenisNosnitsin1970** [comment] 2018-08-15 11:40
Ornamental frame is a decorative band that encompasses the entire writing area, e.g., GMS-002. The manuscripts decorated in such a way are not many, but there are some (usually luxus-books).
Ornamental bands are much more common, an ornamental band extends over one, or two, or three columns of writing (and again there is a difference if it extends over all columns (normally in the incipit of a text), or over some of them, in this case usually marking a subdivision).
This is the basic difference. "Frieze" and "vignette" were not used in Ethio-SPaRe.

**Comment by eu-genia** [comment] 2018-08-15 11:51
type="frame" is present in the E-S records because it was automatically assigned on conversion.
I now replaced it where relevant through "band" in the updated files (except for the cases where frame is mentioned explicitly in the description)
I have not touched the remaining E-S bulk (all the records that do not yet comply with the schema and have no IDs inserted), there for the moment the "frame" remains everywhere

**Comment by Gnisci** [comment] 2018-08-21 11:35
Here is a preliminary list of tentative definitions (open to suggestion and comments):


frame
I take it we are not going to distinguish between frame and band? One could retain a difference, as Denis points out, between horizontal bands and bands that sorround four or three sides (= open frame) of a text or miniature. 

miniature
An indipendent illustration in colour that occupies the full-page or part of the equivalent space of one or more columns of text.

band

A border that surrounds a text or image and may occupy the margins and intercolumnar space. Typically used to mark the beginning of a new text or section of text. (this is the definition if we abandon frame)

drawing
A monochrome or bichrome image that is not painted.

border

Makes sense to drop this and just use band (or band and frame)

diagram
A drawin that conveys information or knowledge in schematic form.

frieze

Makes sense to drop this and just use band (or band and frame)

illustration
Just use miniature or drawing

initial
An enlarged letter at the beginning of a text of paragraph that features figurative or decorative motifs.

marginal
A small miniature painted next to one of the margins of the text.

vignette
To be deleted

engraving
An image on paper created with a printing plate. [n.b.  I assume this term is also going to be used for etchings, but I've never seen any pasted in Ethiopian manuscripts]

**Comment by DenisNosnitsin1970** [comment] 2018-11-22 16:51
Dear Jacopo, 
we should keep the definition between "frame" (fig. 1, or here http://www.bl.uk/onlinegallery/ttp/ethiopic/accessible/pages2and3.html#content) and "band" (fig. 2). This is important. Actually I wonder if also the term "headpiece" can be applied to both.
![1 qds-003_011 ornamental frame](https://user-images.githubusercontent.com/18533839/48914573-23df6b00-ee7c-11e8-885d-afd5fc87768c.JPG)
![2 dd-038 double_0080 ornamental band](https://user-images.githubusercontent.com/18533839/48914587-322d8700-ee7c-11e8-8b07-8802f8dcfa1f.jpg)
![rqg-012_0021](https://user-images.githubusercontent.com/18533839/48914657-6bfe8d80-ee7c-11e8-9ac2-13cc02d4f4b8.JPG)
[3) EMML 9001.docx](https://github.com/BetaMasaheft/Documentation/files/2608804/3.EMML.9001.docx)




A panel of ornament, sometimes incorporating a rubric or heading, that stands at the beginning of a text.", https://www.bl.uk/catalogues/illuminatedmanuscripts/GlossH.asp).  Frames are not frequent but they are usually a sign of a upper quality manuscript production. It would be useful to keep both. 
"Initials" can be dropped.
Another difference: some ornamental bands encompass all text columns, some extend, for instance, over one out of two. Is it worth indicate the difference (in fact headpiece is applicable to the incipit page, right?).
I would easily drop both "border" and "vignette", but please look as the decorations in the margin of fig. 3 and fig. 4 (in the word document). How would you describe them? 
Or here, Orient. 481: http://www.bl.uk/onlinegallery/ttp/ethiopic/accessible/pages26and27.html#content
I have also at least one examples of small narrative uncoloured image in the margin, unrelated to the text. Not too many, but they come out, gradually. 
All they are neither "doodles" nor miniatures; are they "drawings"? The definition of "border" or "vignette" seems to be fitting (http://vocabulaire.irht.cnrs.fr/pages/vocab2.htm).  
Do you have other terms to describe these things? 
Regards - DN

**Comment by Gnisci** [comment] 2018-11-23 15:17
Dear Denis,

Thank you for stimulating an interesting discussion. I do see some advantages, as I noted previously, in retaining _frame_ for borders that delimit more than one side of the text. Frames are, as you say, much less common, so I think there is value in singling them out.

I don't see the advantage of retaining "_headpiece_" as a synonim of _band_. Though I would differentiate between the two: a _headpiece_ has to be horizontal, because it marks the beginning of a text/section whereas a _band_ can be horizontal or vertical (but I've not seen vertical bands by themselves, they are always part of a _frame_)

With regard to your last two point, I would describe the elements in Bl. Or. 481, as "marginal decorations/elements/non-figurative illustrations"

If there are figures that are related to the text and roughly coeval to the production of the unit in which they are found I would describe them as "_marginal illustrations_" and, if they represent a recognizable theme, I would assign an art theme ID to them.

Look forward to hearing your and perhaps @eu-genia and @thea-m 's views.

Best,

Jacopo

**Comment by DenisNosnitsin1970** [comment] 2018-11-23 16:47
I thought "headpiece" with further specification (headpiece: band or headpiece: frame) because it relates to the decoration of an incipit page. Further bands which mark separation of parts of the text are not headpieces, but just bands (fig. 1
![59c sahelo hymnody ms sdmm-macro_0030](https://user-images.githubusercontent.com/18533839/48953865-8f423f00-ef47-11e8-8b2b-f0a0c87d59f6.JPG)

![11 gwahterat genzat gsq-012_0208](https://user-images.githubusercontent.com/18533839/48953751-2fe42f00-ef47-11e8-8ea3-b261efc02d6a.JPG)
).
Do we have something else but "illustrations"? In fact, the small things in the margins do not illustrate anything.
regards - DN

**Comment by DenisNosnitsin1970** [comment] 2018-11-26 10:59
"Marginal illustrations/miniatures/drawings" makes sense for images which are truly painted in the margins.  This is what is meant above with the string: "marginal. A small miniature painted next to one of the margins of the text." but we need one more word in addition to "marginal", don't we? As I understand, such an image is not  "planned" by the craftsman from the very beginning and is not calculated in the layout of the page. 
It is frequently added later and may have no relation to the content. Examples:   
![qarsabar vita of takla haymanot qsm-0250091](https://user-images.githubusercontent.com/18533839/49008251-a82c3980-f16d-11e8-9edf-2d077a136424.JPG)
![qmm-011_090](https://user-images.githubusercontent.com/18533839/49008254-a95d6680-f16d-11e8-99d5-417f980794eb.JPG)
As far as I understand, the term "marginal miniature" is used in manuscript descriptions (http://www.bl.uk/catalogues/illuminatedmanuscripts/results.asp). 

For the crosses and other non-narrative staff, maybe, "marginal design"?
DN

**Comment by eu-genia** [comment] 2018-11-26 11:12
the question of "planned" or not is a different one - any type of image can be added later, a full-page illumination, a harag, anything, not only "marginal" (the above examples surely are not marginal...)
do we need a standard way to encode original vs inserted decoration? or should we use a sdc relation for the added ones? (it might be difficult to be consequent, esp. when there are many decoNotes, but otherwise images/drawings from the syntactic point of view are the same as paratexts whether original or added/donation notes/colophons - and for the moment they are in disadvantage, as we do distinguish between msItems that are part of original plan and additions which are not, while we do not have the distinction for the decorations)

**Comment by Gnisci** [comment] 2018-11-26 16:52
I think @eu-genia  is right when she says that:

> mages/drawings from the syntactic point of view are the same as paratexts whether original or added/donation notes/colophons - and for the moment they are in disadvantage, as we do distinguish between msItems that are part of original plan and additions which are not

@DenisNosnitsin1970 , thanks for comments. Headpiece with two specifications (band or frame) seems also viable to me.

> Do we have something else but "illustrations"? In fact, the small things in the margins do not illustrate anything.

I would also not define the small crosses in the margin of the third example as "illustrations". "Marginal elements"  or "marginal decorations" perhaps?

I would not consider your last example a "marginal" illustration, but more as a "columnar illustration" to borrow the term from Maniaci p. 261: https://user-images.githubusercontent.com/18533839/49008254-a95d6680-f16d-11e8-99d5-417f980794eb.JPG

**Comment by PietroLiuzzo** [comment] 2018-11-27 12:49
We definitely need to summarize this in a proposal for the schema and guidelines, it is for me impossible to summarise the changes to be made. Please make a proposal as in https://github.com/BetaMasaheft/Documentation/issues/888#issuecomment-414643767 with a list with definitions and links to the examples for each. please make sure those link show what you want, not a dead landing page. If possible, examples from the IIIF available images of ES would be much better.
we should not need to updated the guidelines in this case.

**Comment by DenisNosnitsin1970** [comment] 2018-11-27 19:03
Jacopo, when Maniaci speaks about possible positions of miniatures on the page including the "columnar miniatures", she means, at least in my opinion, only "planned miniatures".  In this sense she also has "marginal miniatures". I think we could use both.  
I think the miniatures occupying one full column (as in Maniaci's book) are very rare, I attach an example close to "columnar miniature".  It is very different from two example above as it is clearly a part of an "iconographic program" of the manuscript (there are multiply miniatures in the same style). Esp. the second of my examples above (a saint with cross) was not a part of any program. 

I agree with Zhenja that in many cases it is not obvious and another question is what is actually "later". But from my previous experience, while describing manuscripts for Ethio-SPaRe we used to write smth like "added later", and there are clear cases. Describing manuscripts disfigured with modern miniatures (= modern artistic "additiones"), a cataloguer would make a note on their nature. 

![dsc_3446](https://user-images.githubusercontent.com/18533839/49103643-3393f080-f27c-11e8-8d1d-57bf9adb3759.JPG)

"Marginal decoration" sounds better, but then we can specify, right?
DN

**Comment by eu-genia** [comment] 2018-11-27 19:42
@DenisNosnitsin1970 I believe "planned" vs "unplanned" is a different category as I tried to say. One thing is layout/position, another is whether the illustration belongs to the basic stratum or to an additional one. Let us not confuse things. Columnar, marginal, full-page, intercolumn - or to take examples from the list above, band, vignette, engraving - any of these can belong to either the main stratum or be added. We can discuss with @PietroLiuzzo whether there is a way to better highlight the distinction without having to insist on the SdC relations.

**Comment by PietroLiuzzo** [comment] 2018-11-27 20:34
As stated above, I would really like a summary of the definitions to be added to the schema for use in decoNote, the one above was fine, if it needs updating. Remember that we can have as many values as we want, in as far as they help you filtering the information you want.

If there will be cases of encoding where there is a need to define decoration units and their relation to the stratigraphy of the manuscript we will do that when such a case in the encoding poses the problem, not before.

**Comment by eu-genia** [comment] 2018-11-27 21:05
how about adding the value "added" or similar to the list so that one could have "marginal" but also "marginal added" etc. when it is clear that it was inserted later.

**Comment by Gnisci** [comment] 2019-01-11 13:19
I think we have wrapped this discussion up? @eu-genia ? @DenisNosnitsin1970 ?

**Comment by DenisNosnitsin1970** [comment] 2019-01-15 12:17
Yes, please do.

**Comment by Gnisci** [comment] 2019-02-05 01:43
Apologies for delay, will this do @DenisNosnitsin1970 ?

1.	Doodles = crude drawings which do not belong to the primary strata of the manuscript (already encoded as “extras”)
2.	Drawing = A monochrome or bichrome image that is not painted
3.	Engraving = An image on paper created with a printing plate
4.	Illustration = duplicate of miniature, delete
5.	Initial = An enlarged letter at the beginning of a text of paragraph that features figurative or decorative motifs
6.	Miniature = An independent illustration in colour that occupies the full-page or part of the equivalent space of one or more columns of text
7.	Frieze = not used, delete
8.	Vignette = not used, delete
9.	Headpiece = A decorative border that surrounds a text on one and may occupy the margins and intercolumnar space. Typically used to mark the beginning of a new text or section of text. [with two specifications, for Band (single border) and Frame (border encompassing multiple sides of text)

**Comment by DenisNosnitsin1970** [comment] 2019-03-26 09:24
Dear Jacopo, sorry for delay eather. Yes, the list above will work. Just a couple of questions to the "Headpiece". "multiple sides" - I assume four sides of the text area, right?

**Closed** 2021-02-11 10:12 UTC
Labels: schema
