### ISSUE TITLE
Ethio-SPaRe digital versions

### ISSUE THREAD

**Issue by elambrinaki** [BetaMasaheft/Documentation#1651] opened 2020-12-23 15:53 UTC
@DenisNosnitsin1970 @PietroLiuzzo 
In the faceted search, the following Ethio-SPaRe manucripts come up as having images available, but they aren't loading in the Viewer:
ESap028
ESfbm001

Would it be possible to have access to the images, please?

Also, there might be a typo in the manuscript name on the main page and in the viewer (NSM-005, but the id is ESnsm007) https://betamasaheft.eu/manuscripts/ESnsm007/main

**Comment by PietroLiuzzo** [comment] 2020-12-23 16:00
thanks for pointing out the issue with the images. this is caused by the following markup, not allowed as far as I know.
```xml
 <msItem xml:id="p1_i2">
                        <locus from="32va" to="37rb"/>
                        <title ref="LIT2388Taamme">Miracles of the Trinity</title>
                        <title ref="LIT5066MiraclesMichael">Miracles of St Michael (Taʾāmmǝra Mikāʾel)</title>
                        <title ref="LIT2382Taamme">Miracles of Jesus (Taʾāmmǝra ʾIyasus)</title>
                     </msItem>
```
the same happens in the second example

```xml
<msItem xml:id="ms_i1.4.2">
<locus from="149va" to="179va"/>
<title ref="LIT5673AkkonuColl">Miracles of Mary and ʾAkkonu bǝʾsi compilation</title>
<title type="complete" ref="LIT4274AkkonuB"> ʾAkkonu bǝʾsi... “Does not the man...”</title>
<note>The hymns of ʾAkkonu bǝʾsi are distributed among the miracles of Mary in this block of miracles .</note>
</msItem>
```
There should be only one title in msItem
- [ ] I will check that there is a rule for this and if not add it.
- [ ] I have added a workaround in the iiif.xqm module to take only the first title element
you should be now able to see the images without a problem, but please do not close this issue, so I can complete these tasks

**Comment by PietroLiuzzo** [comment] 2020-12-23 16:12
I have temporarily added a rule, but I am not sure why in the first place this was done. the guidelines do not document this and perhaps someone else remembers why in [52 cases](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3AmsItem%5Bcount%28t%3Atitle%29+gt+1%5D) there are more then one title in a msItem.

**Comment by elambrinaki** [comment] 2020-12-23 16:16
@PietroLiuzzo Thank you very much!

**Comment by DenisNosnitsin1970** [comment] 2020-12-23 16:35
This is probably because the descriptions of the above mentioned manuscripts are not properly adjusted yet, as it is the case with very many Ethio-Spare mss.

**Comment by PietroLiuzzo** [comment] 2020-12-24 05:02
ok, it looked to me like they had been. this means the rule is ok. I will push that.

**Closed** 2020-12-24 05:04 UTC
