### ISSUE TITLE
Explanations about CAe?

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#1247] opened 2019-11-08 13:58 UTC
https://betamasaheft.eu/bibliography?pointer=bm%3AMacomberMiracles&collection=all&fbclid=IwAR379riLmBIFQRREIggUZiXrbqqVHu82lBH7lwjx2kZzOC5pwczeJVgc2wg

My boss is very interested in the Miracles of Mary and I sent her the above link. Since she is not at all related to BM she will clearly not understand the abbreviations CAe... (and also not LIT...) I tried my best to find an explanation for those on your page but failed. Do you have this? Explaining about your concept of Clavis? If not you should have it! CAe is not self-explanatory unfortunately.

Thank you

**Comment by thea-m** [comment] 2019-11-08 14:01
https://github.com/BetaMasaheft/Documentation/issues/1117

**Comment by thea-m** [comment] 2019-11-08 14:44
Despite the improvements especially to the home page carried out after #1117, this is clearly not yet understandable to interested and qualified project external users. Nowhere on the app can an explanation of "CAe" be found, and the abundance of IDs and ID like numbers shown next to the search results when searching for works (for example, Confessio Claudii = CAe 1252 (LIT1252Confes)) can be confusing.
Improving the guidelines and highlighting this on the homepage is certainly good, but does not help those who do not scroll through the homepage when they look for something.

**Comment by PietroLiuzzo** [comment] 2019-11-08 14:55
Every one seems to be very interested in the Miracles of Mary, they are the most interest generating thing we have among our data, I think!

in addition to the pointer given by Dorothea:

The direct link to the guidelines is this: https://betamasaheft.eu/Guidelines/?id=definitionWorks
There are publications explaining this as well, including an article from Dorothea and some pages, which reproduce partially this guidelines page in my book.

We all know is confusing, now, let us start the constructive part: what concrete proposal would you make? where would you want/expect to receive this information in the app? alerts, tooltips, messages on hovering, popups, emails sent, audio messages, etc. 

a user guide to beta masaheft was proposed, but never planned (no one seems to have time for this), but could still be a part of this, which we started to think about several times.

**Comment by thea-m** [comment] 2019-11-08 15:07
I have already proposed, and will continue to do so, to explain the word Clavis (obvious apparently to classicists, not to the entire world) and to explain "CAe". I am aware that the critical point is how to do this, and have no good proposal for this.
Maybe a window with an explanation could pop up when hovering on the CAe number on work pages? 
I know that it is difficult. I would imagine that for @SophiaD-M it would take away some confusion if the IDs were not listed in the search result list, but I find this very practical for my work, for example.

**Comment by PietroLiuzzo** [comment] 2019-11-08 16:24
have a look now on records and clavis list, I have added three types of tooltips on clavis, clavis identifier and the abbreviations of each clavis. see e.g. 
https://betamasaheft.eu/works/list?mainname=&date-range=0%2C2000&cp=&clavistype=CPG&clavisID=&period=
https://betamasaheft.eu/works/list?mainname=&date-range=0%2C2000&cp=&clavistype=CPG&clavisID=&period=

**Comment by thea-m** [comment] 2019-11-08 17:18
Thank you, I think that is much better! @SophiaD-M , what do you think?

**Comment by SophiaD-M** [comment] 2019-11-08 19:22
@PietroLiuzzo yes much better than before. Thank you!
BUT I have to repeat what I said often times, the entire website is very confusing to the eye for people outside of the project. There too many different font sizes, grey boxes, black boxes, orange boxes, bold, italics, fidal, transcription, underlined, arrows, pointing hands, and so on. 
Even I, who has used the app several times, have no idea where or how to find the guidelines. And a user who is even more remote to BM would know even less so.

What I would find very helpful is this (probably super old fashioned, I apologize): 
Let us stay with the example of the Miracles of Mary. If I search for this I would hope that the very FIRST result is exactly this - one main entry for the miracles, providing me with the information that this is not one text but a collection of texts, which BM has divided into 600+ motives, all with their own clavis number. Ideally a short history of the text (originated in France, bla bla, ase Dawit, bla bla). That there is a so called "classic recension of 33 (32?) narratives", that there is a typical set of artistic motives (link). and that there is this list by Macomber out of which you developed the clavis numbers.

In a perfect world you could also indicate the "most important" manuscript, or the oldest, or add  a pretty image, or so, something to please the eye.

**Comment by PietroLiuzzo** [comment] 2019-11-08 21:21
MMM.... if you search "Miracles of Mary" in the app, the main record _is_ eventually the first hit. 
From it you have much more than what you ask. You do have the information about the Macomber list right there, you also have a list of manuscripts which contain the text (or parts of it!) with a link to a view where these are displayed, bibliography of several kinds which all link back to a reverse index so that you know where else an article has been cited, and the list of all independent miracles with an explicit relation, several additional views of this information which are additionally explained by a tour of the page which is right at the top. Among these, related items by keywords, a map of the manuscripts, all attestations of places and persons, if any, etc.  

- [ ] We do not have the image of the manuscripts in the list, no, but that yes, I can do, for those few manuscripts for which we have images, like in the list view.
- [ ] We could had a direct link to a filtered search for decorations in the manuscripts we have and have such annotations 

It is also true that this record in particular has received a priority attention, for very good reasons, to the work of identification and organisation of the miracles.

Conclusion: I am biased.

BUT: while I doubt that we can come up with a solution which pleases all, we can indeed act on specific suggestions like the one above for improvement.

SO: thanks a lot and keep it coming!

**Comment by thea-m** [comment] 2019-11-11 08:03
- LIT2384Taamme is only the first result in the search when searching for "Miracles of Mary" and selecting works. When searching for Miracles of Mary without selecting anything, it is the fourth result of the second category and can require quite some scrolling down. Just to explain that the search experience can differ widely :)
- Many of @SophiaD-M 's suggestions can be addressed by more elaborate abstracts. We (understandably) often do not focus on these, instead preferring to work on other aspects of the records, or editing more records, but it is good to keep in mind that this can be a relatively simple way to increase userfriendliness.
- I agree that most of the info is already there (I have to, since I added it...), but it would be of course nice if not only people in the project can find it. To improve this, it is most helpful to have concrete suggestions, so thank you :)

**Comment by PietroLiuzzo** [comment] 2019-11-11 11:08
after discussion with @SophiaD-M I have added a standard paragraph to all item views listing the relations they contain. Please let me know what you think about it.

**Comment by PietroLiuzzo** [comment] 2019-11-11 13:15
I have also started to draft a help page available from the navigation bar. https://betamasaheft.eu/help.html
if you have comments on the structure and content, ping me here. I am writing it just now.

**Comment by PietroLiuzzo** [comment] 2019-11-12 14:29
I finished the tedious work of drafting this help page. of course TL;DR applies. but if they are really struggling they may put at least the effort of searching this help page. Let me know of any additions, changes, improvement it may need. @eu-genia @sologebre @DenisNosnitsin1970 your feedback would also be useful.

**Closed** 2020-03-11 20:49 UTC
