### ISSUE TITLE
Accept header value interfere with chrome

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1292] opened 2019-12-17 20:00 UTC
When accessing any page under the 'manuscripts' section of the BM website, I get this error, but only in Google Chrome - not in Microsoft Edge

HTTP ERROR 500
Problem accessing /exist/apps/BetMas/manuscripts/list. Reason:

    Server Error
Caused by:
javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMas/manuscripts/list: Invalid Accept Header Value: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' in respect to pattern: '((?:(?:\*\/\*)|(?:[a-z0-9!#\$&\.\+\-\^_]{1,127}\/\*)|(?:[a-z0-9!#\$&\.\+\-\^_]{1,127}\/[a-z0-9!#\$&\.\+\-\^_]{1,127}))(?:;\s?q=(?:0(?:\.[0-9]{1,3})?)|(?:1(?:\.[0]{1,3})?))?\s?(?:;\s?[!#$%&'*+\-.^_`|~0-9a-zA-z]+=[!#$%&'*+\-.^_`|~0-9a-zA-z]+|(?:"[a-z0-9]+"))?)(,\s?(?:(?:\*\/\*)|(?:[a-z0-9!#\$&\.\+\-\^_]{1,127}\/\*)|(?:[a-z0-9!#\$&\.\+\-\^_]{1,127}\/[a-z0-9!#\$&\.\+\-\^_]{1,127}))(?:;\s?q=(?:0(?:\.[0-9]{1,3})?)|(?:1(?:\.[0]{1,3})?))?\s?(?:;\s?[!#$%&'*+\-.^_`|~0-9a-zA-z]+=[!#$%&'*+\-.^_`|~0-9a-zA-z]+|(?:"[a-z0-9]+"))?)*'
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)

I am using Windows 10, which is recently updated, and the most up-to-date version of Chrome, Version 79.0.3945.88

This error has occurred since Monday morning of this week. 

I have deleted all browsing history, cookies, and anything else that might be interfering on my computer, but the error still appears. 

Any suggestions welcome!

**Comment by thea-m** [comment] 2019-12-18 08:53
Still the same for me on chrome at the office desktop (firefox works). On my laptop it works fine with Chrome.

**Comment by PietroLiuzzo** [comment] 2019-12-18 08:54
Thanks for the report. this is an issue with the server cache, which should be easy to fix, but I will not be able to fix before the afternoon.

**Comment by Ralph-Lee-UK** [comment] 2019-12-18 09:10
Many thanks. At least there appears to be a temporary solution, in using Microsoft Edge!

**Comment by PietroLiuzzo** [comment] 2019-12-18 12:56
you should be able now to use the application also in Chrome. This is however a temporary solution with likely backfiring on other sides of the application.

It was not possible to determine now the origin of this issue, localised only in some machines (I could not reproduce the issue myself).

**Comment by thea-m** [comment] 2019-12-18 12:58
Thank you! Let's see what will happen...

**Comment by PietroLiuzzo** [comment] 2019-12-18 13:00
yes, just dont close the issue yet.

I have uncommented  line 88 in our nginx.conf file.

**Comment by Ralph-Lee-UK** [comment] 2019-12-18 13:05
This is now working on Chrome for me.

**Comment by Ralph-Lee-UK** [comment] 2019-12-18 13:05
This is now working on Chrome for me.

**Closed** 2020-03-11 20:13 UTC
