### ISSUE TITLE
count() function for position of msItem leading to timeout 

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1371] opened 2020-03-26 09:15 UTC
I wanted to access https://betamasaheft.eu/works/LIT4033Senkessar/main, but always get 504 Gateway Time-out

**Comment by PietroLiuzzo** [comment] 2020-03-26 16:42
thanks, I have isolated one of the causes and removed it for the time being, but this is not closing this issue, as I am thus removing a feature, which I hope to be able to retrieve with the faceted indexes

**Closed** 2020-05-19 21:10 UTC
Labels: bug, search

**Comment by thea-m** [comment] 2020-05-20 07:36
Thank you!
