### ISSUE TITLE
Donation Note as a work?

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#917] opened 2018-06-12 13:26 UTC
Dear all, 
to encode the content of the manuscript AN-27, I created the following work http://betamasaheft.eu/works/LIT4972Don/main
Thouh a donation note, it seems to circulate independantly and be copied alongside other works.
Please, share your ideas, whther this decision of mine is approporiate?
Many thanks, Daria

**Comment by DenisNosnitsin1970** [comment] 2018-06-12 14:17
This is unusual. Did you transcribe the text in the formular of the manuscript? I am not sure if we can say that this was a text circulating independently. Donation notes used a lot of formulaic language, and the wording may be pretty similar (ze-mäshaf sä-wähabo lä-... negusenä ....). If you see two manuscripts with donation notes formulated in a very similar way, there can be other explanations for this.

**Comment by abausi** [comment] 2018-06-12 14:27
If it can stay alone, independently from the work that follows or precedes, it is an autonomous text, but it is true that such text can be formulaic; it would help to have it transcribed and probably it would be good, to understand better, to give it entirely in the manuscript description

**Comment by DariaElagina** [comment] 2018-06-12 14:38
unfortunately, i do not have the images of this part of the manuscript and have to rely on the description by Stelcyn only. So, it is hardly possible to check whether it is transmitted independently.

**Comment by DariaElagina** [comment] 2018-06-12 15:00
Thanks to the input of Denis, the text schould rather be classified as an inventory list.

**Comment by DenisNosnitsin1970** [comment] 2018-06-12 15:08
"Inventory of..."

**Comment by DariaElagina** [comment] 2018-06-12 15:44
But actually the question remains open, would this text be an indepent work or not? all inventories I could find so far, are rather described as additiones, or just have no reference as here http://betamasaheft.eu/manuscripts/EMML2745/main
In my case, although I cannot prove it, the text of this inventory was rather copied at the same time with the whole manuscript, as this manuscript was apparently copied on the request of Conti Rossini. So, according to guidlines, it can not be an addition...

**Comment by abausi** [comment] 2018-06-12 15:53
But it remains an additional text (it would be "paracontent" in the SFB 
definition, we will have to discuss all this mnroe precisely once): the 
fact that it is copied, does not make it a "work".

Il 12.06.2018 16:44, Daria Elagina ha scritto:

**Comment by DariaElagina** [comment] 2018-06-12 16:08
That is exactly the point.

**Comment by DenisNosnitsin1970** [comment] 2018-06-12 16:58
I think it is important to understand how this compendium was concieved and copied by its creator/owner, and which status was assigned to each of the parts. If I understand correctly, this ms is not a product of the Ethiopian tradition (i have in front of my eyes Conti Rossini 125), but a kind of "colonial manuscript"; maybe, the point should be discussed on examples of purely traditional Ethiopic products (like a land chart entering a hagiographic text, or "chartularies"/ collections of documents like in Orient 481, presubaly accumulating texts scattered in other manuscripts; M.Kropp recently dealt with one very interesting case).

**Comment by eu-genia** [comment] 2018-06-13 07:35
BLorient481 is a good example. I did treat them all as additions, even if they are copied. Sometimes we do have additions which are also independently circulating texts (genealogies, king lists etc.) but these are then still usually encoded as additions with an additional `@ref`.

This once again evidences the problem discussed in this other issue #895 - the current definition of addition as only a thing added later separately makes proper description difficult. copied additions to my mind are still additions. just like copied colophons are still colophons, only of a particular subtype.

AL27 - which actually should be renamed, as our rules say LIBRARYcollectionNumber, so should be AL (or even better ANL, Accademia Nazionale dei Lincei) then cr (for Conti Rossini) then Number, ANLcr27 - is an interesting example of a colonial copy since all the msitems beginning with `ms_i4 `are actually typologically additions.

I would move those msItems to the additions section, even if they are copied together.

**Comment by PietroLiuzzo** [comment] 2018-06-13 08:12
http://betamasaheft.eu/Guidelines/?id=entities-id-structure

**Comment by DenisNosnitsin1970** [comment] 2018-06-13 08:36
I think we should distinguish levels in such texts. There is a codicological criteria for additions and criteria related to the content. This is one thing. If an addition is copied into a continuous text, it changes its status from the codicological point of view. Finally definitions of the additions ("donation note", "ownership note" etc.) are made on formal criteria (specific wording and focus) and delimits small genres of non-literary texts (even "inventory", "list of church feasts" etc.).

**Comment by eu-genia** [comment] 2018-06-13 09:10
The problem is that the guidelines exclude the items which are additions in content but not in form from being able to be encoded as additions.
I would vote for classifying them as additions even without codicological criteria, as already discussed in #895.

**Comment by thea-m** [comment] 2018-06-13 12:07
I would be careful to treat this item as an addition, especially in view of the compilatory character of the entire manuscript. I do not know this particular manuscript and am not an expert on the works contained in it. However, it is my impression (after reading https://www.academia.edu/3022230/Le_Liber_Aksumae_selon_le_manuscrit_Bodleian_Bruce_93_le_plus_ancien_t%C3%A9moin_dun_projet_historiographique_sans_cesse_r%C3%A9activ%C3%A9) , that the so-called “Liber Aksumae” compilation should be treated as a whole as it is present in each manuscript, especially if copied for foreigners, in which case the material included might have been carefully curated under historiographical and political aspects.  How would you decide which units represent here additions (I could imagine arguing that all other units are additions to the Kəbra Nagaśt)? 
(N.B. @DariaElagina, imported EMML manuscripts not described by BM team members should best not be used as examples for our encoding)

**Comment by PietroLiuzzo** [comment] 2018-06-15 20:59
Let me add my two cents and try to summarise. 

I agree with @DenisNosnitsin1970 on the change of status, I think it is a key observation for this conversation. Let me try to rephrase all (just in case this can then be used in the guidelines) 

- The first thing to do is deciding if is addition or content, and perhaps we could update our definitions following the criteria identified by Andrist in the COMSt book (p. 512) to identify strata. Additions would always be quaternary strata whereas copied additions are primary strata.   this could be added to the guidelines if agreeable. In the case in which a manuscript has a donation note which is a "added written element" thus preserving its writing project and the integrity of its content in comparison with the main text, but without  material self stand, than it is an addition, and we encode it as such. If instead the UniProd is part of a primary writing project, the fact that it is copied from an addition does not change the fact that it is an msItem in a msPart or msDesc. Thus the point made by Dorothea holds very true, then the Donation Note in ANL 27 is  a msItem, not an addition.

- The second aspect has to do with deciding if this is then a literary work which gets an ID. From a practical point of view, it would be quite consistent within the architecture. A keyword should then be used to put the text in its correct position as non-literary. We have in the category of keywords for Subjects for example "Other" but also "legal document" and _nothing prevents you_ actually from using one of the keyword for the type of additions. If LIT4972Don is in fact according to the definition in the schema a Donation note, you can add that keyword to the work record. 

- A further separate concern, again agreeing with Denis, is the one about keeping distinct the criteria on which the type of text in an addition (or as said above in a msItem which contains such a text) is defined. If it is an addition, codicologically defined and needs a type, then that type should be assigned according to the definitions which are documented in the schema http://betamasaheft.eu/Guidelines/?id=desc

- "Additionally", if the text is a primary strata UniProd and we happen to have also manuscripts where this text is an addition, then we could add a relation (e.g. saws:isCopyOf ?) which connects the msItem with the addition in question. 

If this is agreeable, then I can update the guidelines accordingly, Daria needs still to decide on the type and add a keyword (donation? inventory?) to the work record.

**Comment by abausi** [comment] 2018-06-16 10:03
Dear Pietro, many thanks, this helps much. To make things even more 
simple, as I also wrote in my contribution, the essential point is that 
an "addition" is a neutral term to indicate that someting is "later 
added" or secondary from the view point of the cataloguer: it should 
NEVER be used to mark a content, that presupposes another perspective. 
To use "additiones" to refer to a certain content is a great mistake. 
Legal documents, deeds etc. are texts like every other texts and in BM 
we need to have a repertory for them; they must be indicated with an 
identifier. Another matter is the unit to which they belong etc.

Il 15.06.2018 21:59, Pietro Liuzzo ha scritto:

**Comment by PietroLiuzzo** [comment] 2018-06-16 13:18
Dear @abausi I think we are getting there. These texts when they are contents will get ids and we will be able to group them and get a repertory by using the keywords. 
The documents corpora page (http://betamasaheft.eu/Guidelines/?id=corpora) is, following this discussion, wrong, and needs to be updated (it should not say that "Documents will be encoded as additions " but rather point to the updated parts of the guidelines where we document the decisions taken here with proper bibliographic references) as well as the example mss BNFabb152, which I add encoded moving the text from the body to the additions (those making it wrong when it was actually correct). However, there is also this extra layer which can be used to group the documents from this persepective. I will make this changes, but I would do with some help for the assigning of work ids to the documents...

**Comment by abausi** [comment] 2018-06-16 13:34
There is no way to say this without looking into each manuscript and 
deciding case by case. This is definitely a task of the philologists.

Il 16.06.2018 14:27, Pietro Liuzzo ha scritto:

**Comment by PietroLiuzzo** [comment] 2018-06-16 13:43
I am happy not to do this, although I would be glad to follow up for the encoding and data structure. Is there any relation between BNFabb152, BLorient418, BDLbruce93 and ANL27 ? Do we have the Dabra Libanos Golden Gospel? I feel we could shortly focus on these and encode them to have a fully and rightly encoded working set of data to also use in the guidelines for future reference

**Comment by abausi** [comment] 2018-06-16 13:46
We have everything, Golden Gospel of Dabra Libanos included. We have 
only to see how to prioritize this work and organize the workflow. It 
will be an important step. We should add a couple of MSS more, like EMML 
1832. We will discuss this.

Il 16.06.2018 14:43, Pietro Liuzzo ha scritto:

**Comment by PietroLiuzzo** [comment] 2018-06-16 13:52
I have searched via the Golden Gospel keyword (http://betamasaheft.eu/authority-files/list?keyword=GoldenGospel) and via dabra libanos as institution (http://betamasaheft.eu/manuscripts/INS0341DL/list) as well via the bibliographic reference to Conti Rossini article (http://betamasaheft.eu/bibliography?pointer=bm%3AContiRossini1901Evangelodoro&collection=all) but I do not seem to be able to find in BM the Golden Gospel of Dabra Libanos...

**Comment by abausi** [comment] 2018-06-16 13:54
It is not in BM: we have in the sense that we have the data. It is 
everything to be inserted. But here the point is to have the pictures of 
the MS. And those we have.

Il 16.06.2018 14:52, Pietro Liuzzo ha scritto:

**Comment by PietroLiuzzo** [comment] 2018-06-18 09:02
@DenisNosnitsin1970 could make a list of the types of additions what need to be given an ID
We will give an id to addition texts

**Comment by PietroLiuzzo** [comment] 2018-06-18 09:08
I will update the guidelines with a summary of the discussion above
@DariaElagina @eu-genia @thea-m will go through the manuscripts they have worked on (@thea-m will also do those of @MassimoVilla) and add ids and create records. 
I will also update the schema and the functions to take titles from items in additions
A new document list should be create taking this works
taxonomy is to be edited to group legal documents according to the above list

**Comment by PietroLiuzzo** [comment] 2018-06-18 12:17
https://github.com/BetaMasaheft/guidelines/pull/3

**Comment by PietroLiuzzo** [comment] 2018-07-19 15:38
This desire is already part of the normal way the encoding works as far as I know. you have always been able to add as many keywords as you wish to a work record and you can use <term/> with the given keyword where you want or use a @corresp to a given id, or use a narrative unit id inside a corresp . so, I do not see anything preventing the additing of futher values to the keyword lists. in the taxonomy, given the useful distinction we have made between deciding if something is main content or addition on one side and deciding which type of text this is on the other, I would not list these as types of additions, as this would be only confusing. these are types of legal documents perhaps, up to you to decide. Remember that these types can be added to the additions of a manuscript directly as we did till now. When we discussed this some of us preferred to give ids to everything, but as far as I can reconstruct from what ended up in the guidelines, We did decide NOT to enforce this and to encode as msItem or addition as needed and to create work record not for each and every addition (which already has an ID where it is in the manuscript!) but only for those where there was a need for grouping. Creating a record for each and every addition so also for normal documents, which appear only as addition in a manuscript would be an overkill (and huge waste of time) in comparison to simply adding the addition in the manuscript record and giving it its type. You can add more than one type or use seg there, i.e. in the addition text inside a manuscript description.
there is also a page of the GL awaiting for content from this conversation (a summary of what has been discussed here) http://betamasaheft.eu/Guidelines/?id=Documents : volunteers? 
http://betamasaheft.eu/Guidelines/?id=additionsVaria is the page edited by the PR above.

**Comment by PietroLiuzzo** [comment] 2018-07-19 15:40
if no volunteers I can do that tomorrow morning.

**Comment by DenisNosnitsin1970** [comment] 2018-07-19 15:52
It would be useful to include the above mentioned types under the additions, as their first and most normal way of circulation is exactly as that of "added writing". They can be copied in a special manuscript and get the status of the main text, and in some cases they are written down in a manuscript from the very beginning. All this is typical mostly for the the documents related to the land tenure system. In some cases, they exist in multiply interrelated versions, in some respects like other literary works. So, there was a need for grouping of these texts (not other types of additional writing), therefore we said that we need ID for them. Do i remember this right?

**Comment by PietroLiuzzo** [comment] 2018-07-19 18:47
Nevermind, after all they have been called like that till now. I will summarise also this last comment and the general principle in the guidelines and try to clarify this ambiguity. I think you can add those freely to the taxonomy as we have added all other values there in the past.

**Comment by PietroLiuzzo** [comment] 2018-07-20 10:07
I have edited the guidelines to reflect this last part of discussion. I do not think I need to be assigned here any more. @DenisNosnitsin1970 can create the keywords which are not yet there and update the schema and taxonomy. It would be nice to add some examples to the guidelines when they are there.

**Comment by thea-m** [comment] 2018-08-01 12:13
For reference, here is the complete list:
[BM Additional notes with ID.docx](https://github.com/BetaMasaheft/Documentation/files/2249352/BM.Additional.notes.with.ID.docx)

**Comment by PietroLiuzzo** [comment] 2018-11-27 10:33
The document needs to be integrated in the GL if it has to be of any relevance to the encoding practices in the project. Please @DenisNosnitsin1970 could you have a go at updating taxonomies and guidelines for this issue, so that we can hopefully close it as it has already been discussed and agreed?

**Comment by DenisNosnitsin1970** [comment] 2018-11-27 12:53
OK, i can do this.

**Comment by PietroLiuzzo** [comment] 2018-11-27 12:56
Thank you very much!

**Comment by PietroLiuzzo** [comment] 2021-02-11 10:21
to close this issue I will 
- [ ] create the authority files based on the above list
- [ ] ask @nafisa-valieva to add keywords to the newly created Works for [DabraLibanosHamGG1](https://betamasaheft.eu/DabraLibanosHamGG1)
- [ ] update the GL with an example from the above ms

**Comment by PietroLiuzzo** [comment] 2021-02-11 14:40
Dear all
in the above linked branch of the Authority-files repository (called NewAdditions) I have added the records, with text from the word document. 
these needs to be fixed, in the branch, before making a PR, but I am not qualified either to fix them or to confirm my draft organization in the taxonomy is ok. please @DariaElagina @eu-genia @thea-m @DenisNosnitsin1970 update the data in the branch.
Examples included in the word file, IMHO should be linked by these authority files and be included in the manuscripts. Again, this is not something I am actually qualified to do, I can try, but one of you would do it quicker and better.
- [ ] Once this is done I will also update the schema with the appropriate values so that the further points of the previous list can be carried out
Thanks!

**Comment by nafisa-valieva** [comment] 2021-02-12 09:59
Dear Pietro,
hi! how do I technically add keywords to the newly created Works for DabraLibanosHamGG1? I add locally in my brunch and then I commit to the master, yes?

**Comment by PietroLiuzzo** [comment] 2021-02-12 10:07
that cannot yet be done, the keywords technically do not yet exist :) but yes, in practice, you will 
- update master of _works_ repository
- make a new branch
- edit the files adding e.g. `<term key="GweltDeed"/>`
- commit to your branch and make a PR. 
The ping here was a sort of pre-warning.
For now, the branch on the _Authority-files_  repository where I pushed commits is still not a PR and contains a lot of information which I tried to put in without much certainty. I think, if you would like to you could also contribute to that. Since it is already an open branch, to see that you simply clone the authority-files repository, update it to the latests status, switch to the NewAdditions branch and you will see the changes I made to the taxonomy.xml file and the added files. you can make your changes to those as well and commit to that branch. 
Same goes for _Manuscripts_ the examples in the word file above could be added to the relevant manuscript records in a dedicated branch and those manuscripts be tagged with the appropriate  `<term/>`.

**Comment by nafisa-valieva** [comment] 2021-02-12 15:10
ok!

**Comment by nafisa-valieva** [comment] 2021-02-12 15:41
I do change some files, check what I did and do not kill me.

**Comment by PietroLiuzzo** [comment] 2021-02-12 19:28
no prob ! which branch on which repo?

**Comment by nafisa-valieva** [comment] 2021-02-12 20:15
Authority-files repository, NewAdditions branch, according to you coordinations!

**Comment by PietroLiuzzo** [comment] 2021-02-12 20:21
I see no issue in those changes, thanks!

**Comment by PietroLiuzzo** [comment] 2021-09-09 11:27
I am closing this issue which got over time a lot of mixed content. I think it is better to start any further discussion fresh. This will in any case remain here for reference.

**Closed by PietroLiuzzo** 2021-09-09 11:27 UTC
Labels: works, encoding, Text Identification
