### ISSUE TITLE
ሰቆቃወ፡ ነፍስ፡ (EMIP 480)

### ISSUE THREAD

**Issue by smaugustine** [BetaMasaheft/Documentation#1506] opened 2020-10-01 16:42 UTC
EMIP 480 item 12 has been erroneously identified as መንገደ፡ ሰማይ፡ (LIT1873Mangad). LIT1873Mangad is for the short prayers attached to copies of ልፋፈ፡ ጽድቅ፡ (as indicated in LIT1758Lefafa).

The text is rather a poem titled ሰቆቃወ፡ ነፍስ፡. This was edited by Getatchew Haile (2017) based on BnF Éth. d'Abbadie 206 and EMML 6993 & 7121, though it also is found in BL Or. 573 and some other manuscripts (including EMIP 480), seemingly unbeknownst to him (unfortunately, since they are meaningfully older witnesses). Note the incipit "በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ዘነበበ። በነቢያቲሁ፡ ...".

This is also a distinct work from LIT2287Saqoqa (also titled ሰቆቃወ፡ ነፍስ፡), which is rather a set of prayers attributed to Athanasius of Alexandria and found in copies of መጽሐፈ፡ ግንዘት፡ (where it is titled "ዘእምቃለ፡ አትናቴዎስ፡ ዘይኤምር፡ ሰቆቃወ፡ ነፍስ፡ ..." and begins "ንዑ፡ ተጋብኡ፡ ኵልክሙ፡ አንትሙ፡ እለ፡ ሕያዋን፡ ...".

I don't find any work record for this, the poem ሰቆቃወ፡ ነፍስ፡, and so it would seem that we should create one for it and correct EMIP 480.

**Comment by Ralph-Lee-UK** [comment] 2020-10-02 08:35
@smaugustine Many thanks for spotting this. There are several other unidentified works in this record. I will raise an issue in the documentation section, and add some images to start the process of creating new work files

**Comment by eu-genia** [comment] 2020-10-02 08:53
Thank you @smaugustine - please go ahead with creating the record, then @Ralph-Lee-UK can take care of correcting EMIP 480 and checking the other works

**Comment by smaugustine** [comment] 2020-10-02 10:16
@Ralph-Lee-UK I have been working on a thorough comparison of መልክአ፡ ጉባኤ፡ manuscripts. I was actually hoping to go through 480 for my own notes, but the iiif manifest is broken and so the images don't appear in the Beta Masaheft viewer.

**Comment by eu-genia** [comment] 2020-10-02 10:22
@PietroLiuzzo can you check what is wrong with https://betamasaheft.eu/api/iiif/EMIP00480/manifest?

**Comment by PietroLiuzzo** [comment] 2020-10-02 10:24
the fix has been available for 10 days... https://github.com/BetaMasaheft/Manuscripts/pull/790

**Comment by eu-genia** [comment] 2020-10-02 10:27
Thank you - before this has been corrected and merged you can check the images directly here https://betamasaheft.eu/iiif/EMIP/Codices/480/043.tif/full/full/0/default.jpg
https://betamasaheft.eu/iiif/EMIP/Codices/480/044.tif/full/full/0/default.jpg
etc

**Comment by PietroLiuzzo** [comment] 2020-10-02 10:28
the fix can be merged without any problem IMHO. it was just a few missing #

**Comment by Ralph-Lee-UK** [comment] 2020-10-02 10:33
@smaugustine this is great. 
In case it is easier for you to work with in checking the contents, there is a PDF of this manuscript at this link, which you should be able to download. 
https://drive.google.com/file/d/1m5NJLsujCJW5Iuo0V4foe5n2q65kLq0a/view?usp=sharing
I have just made some edits to the EMIP 480 record, because there are several other errors in that record, as well as works that are unidentified. How soon are you planning to make any changes? Normally our edits are merged by Pietro late on Wednesday or on Thursday morning, so these changes will be made available around then. If you want to work on it before then I have just pushed these minor changes to the branch that we are working on this week, which is EMIP-Metadata-1-October-2020 so you could edit that version. Does that sound OK?

**Comment by Ralph-Lee-UK** [comment] 2020-10-02 10:35
@PietroLiuzzo I see that you have some changes that are not merged. It seems that it would be best that I don't include my changes before yours are merged?

**Comment by PietroLiuzzo** [comment] 2020-10-02 10:38
do not worry, if you reproduce in your branch my few and minor changes, then my branch can simply be removed. I doubt that in any case this is likely to cause any major conflict. 
Please, note that I will be on holidays from tomorrow until 18 October. please assign PRs for the next two weeks to other team members who can validate and merge instead of me, I will keep far from any internet-bound machine.

**Comment by eu-genia** [comment] 2020-10-02 10:56
I have merged the latest fix (LIT1854Malkea replaced through LIT6191Malkea)

**Comment by Ralph-Lee-UK** [comment] 2020-10-02 12:04
@PietroLiuzzo and @eu-genia I have downloaded the file with both of your changes, and added mine, so @smaugustine I will shortly push my edits to the branch that I mentioned above, if you could make your changes there?

**Comment by smaugustine** [comment] 2020-10-02 12:17
@Ralph-Lee-UK sounds good!

**Comment by Ralph-Lee-UK** [comment] 2020-10-02 12:22
@smaugustine That version is now pushed. There are several errors in this - the previous editor was a little over confident in assigning things, but as you're going to check this this will put these right! If you need any other images of EMIP files please just ask, as we are working at getting them both uploaded and then linked up with the ms files, but not all of them are done yet.

**Closed by Ralph-Lee-UK** 2020-10-02 12:22 UTC
Labels: Text Identification, works

**Comment by Ralph-Lee-UK** [comment] 2020-10-08 07:54
@smaugustine I have another  መልክአ፡ ጉባኤ, EMIP 764. I will be posting some questions about it shortly, because there are one or two works in it that I cannot identify. The image set for this manuscript needs some work, as there are duplicate shots, etc. so we won't be putting the full set on BM for a little while. I was wondering if in addition to my questions whether you would be interested in a PDF of the whole manuscript? It is a 19th century manuscript.

**Comment by smaugustine** [comment] 2020-10-08 08:40
@Ralph-Lee-UK For sure, this sort of stuff is my jam :)

**Comment by Ralph-Lee-UK** [comment] 2020-10-08 08:54
@smaugustine you can download it from this link 
https://1drv.ms/b/s!AsYm6VrVJ3xVlagaP61WpsMo3wXHsA?e=CsfQoe
I will post an issue shortly listing the works that I have not been able to identify
